# Generated by Django 3.2.9 on 2021-11-06 10:37

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploadmodel',
            name='avatar',
            field=models.ImageField(blank=True, default='/profiles/profile.png', upload_to=app.models.username),
        ),
    ]
